import Image from "next/image";

export type Pair = {
  sku: string;
  name: string;
  surface: string;
  scene: string;
  before: string;
  after: string;
};

/**
 * Editorial composed before/after — small "before" card overlaps the
 * dominant "after" image. Not a slider; the transformation reads instantly.
 */
export function BeforeAfter({ pair }: { pair: Pair }) {
  return (
    <figure className="relative aspect-[4/5] w-full">
      {/* Dominant after image */}
      <div className="absolute inset-0 overflow-hidden rounded-xl border border-line-soft bg-paper-2 shadow-soft">
        <Image
          src={pair.after}
          alt={`${pair.name}: lifestyle photograph generated by Vesperdrop, ${pair.scene.toLowerCase()}`}
          fill
          priority
          sizes="(max-width: 768px) 100vw, 50vw"
          className="object-cover"
        />
        <span className="absolute bottom-4 left-4 inline-flex items-center rounded-full bg-cream/95 px-3 py-1 font-mono text-[10px] uppercase tracking-[0.12em] text-ink shadow-subtle">
          After · Vesperdrop
        </span>
      </div>

      {/* Smaller before card, overlapping top-left, slightly tilted */}
      <div
        className="absolute left-[6%] top-[8%] w-[36%] overflow-hidden rounded-md border border-line bg-cream shadow-card"
        style={{ transform: "rotate(-3deg)" }}
      >
        <div className="relative aspect-[4/5]">
          <Image
            src={pair.before}
            alt={`${pair.name}: original product photo, ${pair.surface.toLowerCase()}`}
            fill
            priority
            sizes="(max-width: 768px) 36vw, 18vw"
            className="object-cover"
          />
          <span className="absolute left-2 top-2 inline-flex items-center rounded-sm bg-ink/85 px-2 py-0.5 font-mono text-[9px] uppercase tracking-[0.16em] text-cream backdrop-blur-sm">
            Before
          </span>
        </div>
        <figcaption className="px-3 py-2 font-mono text-[9px] uppercase tracking-[0.14em] text-ink-3">
          Your photo
        </figcaption>
      </div>
    </figure>
  );
}
