import Image from "next/image";
import Link from "next/link";

export function Hero() {
  return (
    <section className="border-b border-[var(--color-line)]">
      <div className="mx-auto grid max-w-6xl grid-cols-1 gap-12 px-6 py-20 md:grid-cols-[1.1fr_1fr] md:gap-16 md:py-28">
        <div className="flex flex-col justify-center">
          <p className="mb-6 font-mono text-[10px] uppercase tracking-[0.18em] text-[var(--color-ink-3)]">
            Lifestyle photography, generated
          </p>
          <h1 className="font-serif text-5xl font-light leading-[0.96] tracking-tight text-[var(--color-ink)] md:text-7xl">
            Your product,
            <br />
            <span className="italic font-light">on location</span>.
            <br />
            <span className="text-[var(--color-ember)]">In minutes.</span>
          </h1>
          <p className="mt-8 max-w-md font-serif text-xl font-light leading-relaxed text-[var(--color-ink-3)]">
            Drop in a flat product shot. Darkroom returns a batch of lifestyle
            photographs &mdash; ready for your Shopify store, Amazon listing, and
            ads.
          </p>
          <div className="mt-10 flex flex-wrap items-center gap-4">
            <Link
              href="/sign-up"
              className="inline-flex items-center rounded-full bg-[var(--color-ember)] px-6 py-3 text-sm font-medium text-[var(--color-cream)] transition-colors hover:bg-[#a83c18]"
            >
              Start free
            </Link>
            <Link
              href="/pricing"
              className="border-b border-[var(--color-ink)] pb-1 text-sm text-[var(--color-ink)] transition-colors hover:border-[var(--color-ember)] hover:text-[var(--color-ember)]"
            >
              See pricing
            </Link>
          </div>
        </div>

        <div className="relative aspect-[4/5] w-full overflow-hidden rounded-sm bg-[var(--color-ink)]">
          <Image
            src="/marketing/jacket_after.png"
            alt="Lifestyle product photograph generated by Darkroom"
            fill
            sizes="(min-width: 768px) 40vw, 100vw"
            className="object-cover"
            priority
          />
          <div className="absolute left-3 top-3 inline-flex items-center border border-white/30 bg-black/40 px-2 py-1 font-mono text-[10px] tracking-[0.18em] text-[var(--color-cream)] backdrop-blur-sm">
            INPUT &middot; YOUR PHOTO
          </div>
          <div className="absolute right-3 top-3 inline-flex items-center bg-[var(--color-ember)] px-2 py-1 font-mono text-[10px] tracking-[0.18em] text-[var(--color-cream)]">
            OUTPUT &middot; DARKROOM
          </div>
          <div className="absolute inset-x-0 bottom-0 flex items-center justify-between bg-gradient-to-t from-black/60 to-transparent px-3 py-3 font-mono text-[10px] tracking-[0.16em] text-[var(--color-cream)]">
            <span>FIG. 01 &mdash; CROPPED DENIM JACKET</span>
            <span className="opacity-70">HOTEL BANQUETTE &middot; GOLDEN HOUR</span>
          </div>
        </div>
      </div>
    </section>
  );
}
